// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protobufs/variable.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExpectedStateVariable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Var1 int64  `protobuf:"varint,1,opt,name=var1,proto3" json:"var1,omitempty"`
	Var2 string `protobuf:"bytes,2,opt,name=var2,proto3" json:"var2,omitempty"`
}

func (x *ExpectedStateVariable) Reset() {
	*x = ExpectedStateVariable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_variable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpectedStateVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpectedStateVariable) ProtoMessage() {}

func (x *ExpectedStateVariable) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_variable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpectedStateVariable.ProtoReflect.Descriptor instead.
func (*ExpectedStateVariable) Descriptor() ([]byte, []int) {
	return file_protobufs_variable_proto_rawDescGZIP(), []int{0}
}

func (x *ExpectedStateVariable) GetVar1() int64 {
	if x != nil {
		return x.Var1
	}
	return 0
}

func (x *ExpectedStateVariable) GetVar2() string {
	if x != nil {
		return x.Var2
	}
	return ""
}

type PingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_variable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_variable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_protobufs_variable_proto_rawDescGZIP(), []int{1}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_variable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_variable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_variable_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type ContractVariableStateCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateCheck   string `protobuf:"bytes,1,opt,name=stateCheck,proto3" json:"stateCheck,omitempty"`
	StateMessage string `protobuf:"bytes,2,opt,name=stateMessage,proto3" json:"stateMessage,omitempty"`
}

func (x *ContractVariableStateCheck) Reset() {
	*x = ContractVariableStateCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_variable_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractVariableStateCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractVariableStateCheck) ProtoMessage() {}

func (x *ContractVariableStateCheck) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_variable_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractVariableStateCheck.ProtoReflect.Descriptor instead.
func (*ContractVariableStateCheck) Descriptor() ([]byte, []int) {
	return file_protobufs_variable_proto_rawDescGZIP(), []int{3}
}

func (x *ContractVariableStateCheck) GetStateCheck() string {
	if x != nil {
		return x.StateCheck
	}
	return ""
}

func (x *ContractVariableStateCheck) GetStateMessage() string {
	if x != nil {
		return x.StateMessage
	}
	return ""
}

type ContractVariableState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Var1 int64  `protobuf:"varint,1,opt,name=var1,proto3" json:"var1,omitempty"`
	Var2 string `protobuf:"bytes,2,opt,name=var2,proto3" json:"var2,omitempty"`
}

func (x *ContractVariableState) Reset() {
	*x = ContractVariableState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_variable_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractVariableState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractVariableState) ProtoMessage() {}

func (x *ContractVariableState) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_variable_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractVariableState.ProtoReflect.Descriptor instead.
func (*ContractVariableState) Descriptor() ([]byte, []int) {
	return file_protobufs_variable_proto_rawDescGZIP(), []int{4}
}

func (x *ContractVariableState) GetVar1() int64 {
	if x != nil {
		return x.Var1
	}
	return 0
}

func (x *ContractVariableState) GetVar2() string {
	if x != nil {
		return x.Var2
	}
	return ""
}

var File_protobufs_variable_proto protoreflect.FileDescriptor

var file_protobufs_variable_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x76, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e,
	0x22, 0x3f, 0x0a, 0x15, 0x45, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x76, 0x61, 0x72, 0x31, 0x12, 0x12, 0x0a,
	0x04, 0x76, 0x61, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x72,
	0x32, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x22, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x22, 0x60, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x76,
	0x61, 0x72, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x32, 0x32, 0x3f, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x50, 0x43, 0x12, 0x34, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x61, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x75,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x55, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1b, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x20, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobufs_variable_proto_rawDescOnce sync.Once
	file_protobufs_variable_proto_rawDescData = file_protobufs_variable_proto_rawDesc
)

func file_protobufs_variable_proto_rawDescGZIP() []byte {
	file_protobufs_variable_proto_rawDescOnce.Do(func() {
		file_protobufs_variable_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_variable_proto_rawDescData)
	})
	return file_protobufs_variable_proto_rawDescData
}

var file_protobufs_variable_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobufs_variable_proto_goTypes = []interface{}{
	(*ExpectedStateVariable)(nil),      // 0: main.ExpectedStateVariable
	(*PingMessage)(nil),                // 1: main.PingMessage
	(*PingResponse)(nil),               // 2: main.PingResponse
	(*ContractVariableStateCheck)(nil), // 3: main.ContractVariableStateCheck
	(*ContractVariableState)(nil),      // 4: main.ContractVariableState
}
var file_protobufs_variable_proto_depIdxs = []int32{
	1, // 0: main.PingRPC.PingCheck:input_type -> main.PingMessage
	4, // 1: main.Actuator.ContractStateCheck:input_type -> main.ContractVariableState
	2, // 2: main.PingRPC.PingCheck:output_type -> main.PingResponse
	3, // 3: main.Actuator.ContractStateCheck:output_type -> main.ContractVariableStateCheck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufs_variable_proto_init() }
func file_protobufs_variable_proto_init() {
	if File_protobufs_variable_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_variable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpectedStateVariable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_variable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_variable_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_variable_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractVariableStateCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_variable_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractVariableState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_variable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobufs_variable_proto_goTypes,
		DependencyIndexes: file_protobufs_variable_proto_depIdxs,
		MessageInfos:      file_protobufs_variable_proto_msgTypes,
	}.Build()
	File_protobufs_variable_proto = out.File
	file_protobufs_variable_proto_rawDesc = nil
	file_protobufs_variable_proto_goTypes = nil
	file_protobufs_variable_proto_depIdxs = nil
}
